### ISSUE TITLE
Need for better RWD version

### ISSUE THREAD

**Issue by iniluap** [iniluap/rgb-guessing-game#1]
- The RGB value in the header needs scaling, so that it doesn't wrap.
- When a device is narrower than 425px, the boxes with colors should become rectangular, with width equal to their parent and height of 75px.

**Comment by iniluap** [comment]
How it looks currently on small devices:

![iniluap github io_rgb-guessing-game_ galaxy s5](https://user-images.githubusercontent.com/20014410/35827131-277bc20e-0abb-11e8-80d2-3fa7edadd2f1.png)

**Comment by tristandenyer** [comment]
I'm going to work on this tonight.
